os: 
  - windows
  - linux
language: cpp
#dist: windows
compiler:
  - clang
install:
#install python
  - sudo apt install python3
  - sudo apt-get install libgl1-mesa-dri
  - python --version
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
# Download dependencies and build project
  - conan install . --profile msvc16
# Call your build system
  - cmake . -G "Visual Studio 2019"
  - cmake --build .
# Run your tests
#  - ctest .
